// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {base} from '../models';
import {menu} from '../models';
import {preferences} from '../models';
import {utils} from '../models';
import {context} from '../models';
import {project} from '../models';
import {sdk} from '../models';
import {names} from '../models';
import {app} from '../models';
import {crud} from '../models';

export function BuildDalleDressForProject():Promise<Record<string, any>>;

export function CancelAllFetches():Promise<number>;

export function CancelFetch(arg1:types.DataFacet):Promise<void>;

export function ChangeImageStorageLocation(arg1:string):Promise<void>;

export function CloseProject(arg1:string):Promise<void>;

export function ConvertToAddress(arg1:string):Promise<base.Address|boolean>;

export function FileNew(arg1:menu.CallbackData):Promise<void>;

export function FileOpen(arg1:menu.CallbackData):Promise<void>;

export function FileQuit(arg1:menu.CallbackData):Promise<void>;

export function FileSave(arg1:menu.CallbackData):Promise<void>;

export function FileSaveAs(arg1:menu.CallbackData):Promise<void>;

export function GetAppId():Promise<preferences.Id>;

export function GetAppPreferences():Promise<preferences.AppPreferences>;

export function GetChainList():Promise<utils.ChainList>;

export function GetContext():Promise<context.Context>;

export function GetFilename():Promise<project.Project>;

export function GetImageURL(arg1:string):Promise<string>;

export function GetLanguage():Promise<string>;

export function GetLastAddress():Promise<string>;

export function GetLastChain():Promise<string>;

export function GetLastTab(arg1:string):Promise<types.DataFacet>;

export function GetMarkdown(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetNamesPage(arg1:types.Payload,arg2:number,arg3:number,arg4:sdk.SortSpec,arg5:string):Promise<names.NamesPage>;

export function GetNamesSummary(arg1:types.Payload):Promise<types.Summary>;

export function GetNodeStatus():Promise<types.MetaData>;

export function GetOpenProjects():Promise<Array<Record<string, any>>>;

export function GetOrgPreferences():Promise<preferences.OrgPreferences>;

export function GetProjectAddress():Promise<base.Address>;

export function GetTheme():Promise<string>;

export function GetUserInfoStatus():Promise<app.UserInfoStatus>;

export function GetUserPreferences():Promise<preferences.UserPreferences>;

export function GetWizardReturn():Promise<string>;

export function IsInitialized():Promise<boolean>;

export function IsReady():Promise<boolean>;

export function LogBackend(arg1:string):Promise<void>;

export function LogFrontend(arg1:string):Promise<void>;

export function NameFromAddress(arg1:string):Promise<types.Name|boolean>;

export function NamesCrud(arg1:types.Payload,arg2:crud.Operation,arg3:types.Name):Promise<void>;

export function RegisterCollection(arg1:types.Collection):Promise<void>;

export function Reload(arg1:types.Payload):Promise<void>;

export function ReloadNames(arg1:types.Payload):Promise<void>;

export function ResetStore(arg1:string):Promise<void>;

export function SaveBounds(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetAppPreferences(arg1:preferences.AppPreferences):Promise<void>;

export function SetChain(arg1:preferences.Chain):Promise<void>;

export function SetHelpCollapsed(arg1:boolean):Promise<void>;

export function SetInitialized(arg1:boolean):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetLastAddress(arg1:string):Promise<void>;

export function SetLastChain(arg1:string):Promise<void>;

export function SetLastTab(arg1:string,arg2:types.DataFacet):Promise<void>;

export function SetLastView(arg1:string):Promise<void>;

export function SetMenuCollapsed(arg1:boolean):Promise<void>;

export function SetOrgPreferences(arg1:preferences.OrgPreferences):Promise<void>;

export function SetProjectAddress(arg1:base.Address):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetUserInfo(arg1:string,arg2:string):Promise<void>;

export function SetUserPreferences(arg1:preferences.UserPreferences):Promise<void>;

export function SwitchToProject(arg1:string):Promise<void>;
