// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildDalleDressForProject() {
  return window['go']['app']['App']['BuildDalleDressForProject']();
}

export function CancelAllFetches() {
  return window['go']['app']['App']['CancelAllFetches']();
}

export function CancelFetch(arg1) {
  return window['go']['app']['App']['CancelFetch'](arg1);
}

export function ChangeImageStorageLocation(arg1) {
  return window['go']['app']['App']['ChangeImageStorageLocation'](arg1);
}

export function CloseProject(arg1) {
  return window['go']['app']['App']['CloseProject'](arg1);
}

export function ConvertToAddress(arg1) {
  return window['go']['app']['App']['ConvertToAddress'](arg1);
}

export function FileNew(arg1) {
  return window['go']['app']['App']['FileNew'](arg1);
}

export function FileOpen(arg1) {
  return window['go']['app']['App']['FileOpen'](arg1);
}

export function FileQuit(arg1) {
  return window['go']['app']['App']['FileQuit'](arg1);
}

export function FileSave(arg1) {
  return window['go']['app']['App']['FileSave'](arg1);
}

export function FileSaveAs(arg1) {
  return window['go']['app']['App']['FileSaveAs'](arg1);
}

export function GetAppId() {
  return window['go']['app']['App']['GetAppId']();
}

export function GetAppPreferences() {
  return window['go']['app']['App']['GetAppPreferences']();
}

export function GetChainList() {
  return window['go']['app']['App']['GetChainList']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetFilename() {
  return window['go']['app']['App']['GetFilename']();
}

export function GetImageURL(arg1) {
  return window['go']['app']['App']['GetImageURL'](arg1);
}

export function GetLanguage() {
  return window['go']['app']['App']['GetLanguage']();
}

export function GetLastAddress() {
  return window['go']['app']['App']['GetLastAddress']();
}

export function GetLastChain() {
  return window['go']['app']['App']['GetLastChain']();
}

export function GetLastTab(arg1) {
  return window['go']['app']['App']['GetLastTab'](arg1);
}

export function GetMarkdown(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetMarkdown'](arg1, arg2, arg3);
}

export function GetNamesPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetNamesPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetNamesSummary(arg1) {
  return window['go']['app']['App']['GetNamesSummary'](arg1);
}

export function GetNodeStatus() {
  return window['go']['app']['App']['GetNodeStatus']();
}

export function GetOpenProjects() {
  return window['go']['app']['App']['GetOpenProjects']();
}

export function GetOrgPreferences() {
  return window['go']['app']['App']['GetOrgPreferences']();
}

export function GetProjectAddress() {
  return window['go']['app']['App']['GetProjectAddress']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function GetUserInfoStatus() {
  return window['go']['app']['App']['GetUserInfoStatus']();
}

export function GetUserPreferences() {
  return window['go']['app']['App']['GetUserPreferences']();
}

export function GetWizardReturn() {
  return window['go']['app']['App']['GetWizardReturn']();
}

export function IsInitialized() {
  return window['go']['app']['App']['IsInitialized']();
}

export function IsReady() {
  return window['go']['app']['App']['IsReady']();
}

export function LogBackend(arg1) {
  return window['go']['app']['App']['LogBackend'](arg1);
}

export function LogFrontend(arg1) {
  return window['go']['app']['App']['LogFrontend'](arg1);
}

export function NameFromAddress(arg1) {
  return window['go']['app']['App']['NameFromAddress'](arg1);
}

export function NamesCrud(arg1, arg2, arg3) {
  return window['go']['app']['App']['NamesCrud'](arg1, arg2, arg3);
}

export function RegisterCollection(arg1) {
  return window['go']['app']['App']['RegisterCollection'](arg1);
}

export function Reload(arg1) {
  return window['go']['app']['App']['Reload'](arg1);
}

export function ReloadNames(arg1) {
  return window['go']['app']['App']['ReloadNames'](arg1);
}

export function ResetStore(arg1) {
  return window['go']['app']['App']['ResetStore'](arg1);
}

export function SaveBounds(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveBounds'](arg1, arg2, arg3, arg4);
}

export function SetAppPreferences(arg1) {
  return window['go']['app']['App']['SetAppPreferences'](arg1);
}

export function SetChain(arg1) {
  return window['go']['app']['App']['SetChain'](arg1);
}

export function SetHelpCollapsed(arg1) {
  return window['go']['app']['App']['SetHelpCollapsed'](arg1);
}

export function SetInitialized(arg1) {
  return window['go']['app']['App']['SetInitialized'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}

export function SetLastAddress(arg1) {
  return window['go']['app']['App']['SetLastAddress'](arg1);
}

export function SetLastChain(arg1) {
  return window['go']['app']['App']['SetLastChain'](arg1);
}

export function SetLastTab(arg1, arg2) {
  return window['go']['app']['App']['SetLastTab'](arg1, arg2);
}

export function SetLastView(arg1) {
  return window['go']['app']['App']['SetLastView'](arg1);
}

export function SetMenuCollapsed(arg1) {
  return window['go']['app']['App']['SetMenuCollapsed'](arg1);
}

export function SetOrgPreferences(arg1) {
  return window['go']['app']['App']['SetOrgPreferences'](arg1);
}

export function SetProjectAddress(arg1) {
  return window['go']['app']['App']['SetProjectAddress'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['app']['App']['SetTheme'](arg1);
}

export function SetUserInfo(arg1, arg2) {
  return window['go']['app']['App']['SetUserInfo'](arg1, arg2);
}

export function SetUserPreferences(arg1) {
  return window['go']['app']['App']['SetUserPreferences'](arg1);
}

export function SwitchToProject(arg1) {
  return window['go']['app']['App']['SwitchToProject'](arg1);
}
